services:
  task-service:
    build: ./task-service
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskdb
      SPRING_DATASOURCE_USERNAME: adham
      SPRING_DATASOURCE_PASSWORD: mcse1234
    depends_on:
      - postgres

  user-service:
    build: ./user-service
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskdb
      SPRING_DATASOURCE_USERNAME: adham
      SPRING_DATASOURCE_PASSWORD: mcse1234
    depends_on:
      - postgres

  prayer-service:
    build: ./prayer-service
    ports:
      - "3001:3001"
    environment:
      MONGO_URI: "mongodb://mongo:27017/prayerDB"
      API_URL: "https://api.aladhan.com/v1/timingsByCity"
    depends_on:
      - mongo
    networks:
      - backend

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  postgres:
    image: postgres:17.3
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: adham
      POSTGRES_PASSWORD: mcse1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - "mongo_data:/data/db"
    networks:
      - backend

volumes:
  postgres_data:
  mongo_data:

networks:
  backend: