version: '3.8'
services:
  task-service:
    build: ./task-service
    ports:
      - "8081:8080"
  user-service:
    build: ./user-service
    ports:
      - "8082:8080"
  prayer-service:
    build: ./prayer-service
    ports:
      - "3001:3000"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
