apiVersion: apps/v1
kind: Deployment
metadata:
  name: prayer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prayer-service
  template:
    metadata:
      labels:
        app: prayer-service
    spec:
      containers:
      - name: prayer-service
        image: hopemcsese/prayer-service:latest
        ports:
        - containerPort: 3001
        env:
        - name: MONGO_URI
          value: mongodb://10.255.200.52:27017/prayerDB
        - name: API_URL
          value: https://api.aladhan.com/v1/timingsByCity
---
apiVersion: v1
kind: Service
metadata:
  name: prayer-service
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: prayer-service
