apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-prayer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-prayer-service
  template:
    metadata:
      labels:
        app: user-prayer-service
    spec:
      containers:
      - name: user-prayer-service
        image: hopemcsese/user-prayer-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://10.255.200.52:5432/taskdb
        - name: SPRING_DATASOURCE_USERNAME
          value: adham
        - name: SPRING_DATASOURCE_PASSWORD
          value: mcse1234
---
apiVersion: v1
kind: Service
metadata:
  name: user-prayer-service
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8080
  selector:
    app: user-prayer-service
